# Generated by Django 3.1.7 on 2021-04-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('company_id', 'name')},
        ),
    ]
