# Generated by Django 3.1.7 on 2021-04-15 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='letter',
            field=models.ForeignKey(db_column='letter_id', on_delete=django.db.models.deletion.DO_NOTHING, to='myauth.letter2'),
        ),
    ]
