# Generated by Django 3.1.7 on 2021-04-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_auto_20210407_1235'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('company_id', 'name')},
        ),
    ]
