# Generated by Django 3.1.7 on 2021-04-15 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_auto_20210407_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company2',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'unique_together': {('company_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Letter2',
            fields=[
                ('letter_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=10000, null=True)),
                ('question', models.CharField(blank=True, max_length=1000, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myauth.company2')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myauth.task2')),
            ],
        ),
    ]
