# Generated by Django 3.1.7 on 2021-04-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_company2_letter2_task2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter2',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='letter2',
            old_name='task_id',
            new_name='task',
        ),
    ]
